name: Publish to S3

on:
  push:
    # branches: ["main"]
    branches: ["*"]

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload Assets
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          endpoint: ${{ secrets.AWS_S3_ENDPOINT }}
          source_dir: '.'
          destination_dir: ''
